name: Sync to CodeCommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@main
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Sync app to CodeCommit
      uses: kdanylo/aws-code-pipeline@main
      with:
        repository.name: java-apps
        aws-region: us-east-2
